# Generated by Django 3.2.3 on 2021-09-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
