# Generated by Django 3.2.5 on 2021-09-30 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210922_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctv_history', models.ManyToManyField(related_name='CCTV_Purchase', to='website.Cctv')),
                ('cctv_wishlist', models.ManyToManyField(related_name='CCTV_wishlist', to='website.Cctv')),
                ('product_history', models.ManyToManyField(related_name='Product_Purchase', to='website.Products')),
                ('product_wishlist', models.ManyToManyField(related_name='Product_wishlist', to='website.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
