# Generated by Django 3.2.5 on 2021-10-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='auth.group'),
        ),
    ]
