# Generated by Django 3.2.5 on 2021-10-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_user_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cctv_history',
            field=models.ManyToManyField(blank=True, related_name='CCTV_Purchase', to='website.Cctv'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cctv_wishlist',
            field=models.ManyToManyField(blank=True, related_name='CCTV_wishlist', to='website.Cctv'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='product_history',
            field=models.ManyToManyField(blank=True, related_name='Product_Purchase', to='website.Products'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='product_wishlist',
            field=models.ManyToManyField(blank=True, related_name='Product_wishlist', to='website.Products'),
        ),
    ]
