# Generated by Django 3.2.5 on 2021-10-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20211002_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cctv_history',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='product_history',
        ),
    ]
