# Generated by Django 3.2.6 on 2021-10-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20211003_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pdesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='pname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ppic',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='pprice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cctv_wishlist',
        ),
        migrations.AddField(
            model_name='products',
            name='isCctv',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Cctv',
        ),
    ]
